export const SEAT_MAP_32B = [
  {
    equipmentModel: "32B",
    seatRows: [
      [
        {
          designator: "01A",
          row: 1,
          column: "A",
          group: 3,
          legend: 1,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: true,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "01B",
          row: 1,
          column: "B",
          group: 3,
          legend: 1,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: true,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "01C",
          row: 1,
          column: "C",
          group: 3,
          legend: 1,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: true,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 1,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "01D",
          row: 1,
          column: "D",
          group: 3,
          legend: 1,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: true,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "01E",
          row: 1,
          column: "E",
          group: 3,
          legend: 1,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: true,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "01F",
          row: 1,
          column: "F",
          group: 3,
          legend: 1,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: true,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "02A",
          row: 2,
          column: "A",
          group: 1,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "02B",
          row: 2,
          column: "B",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "02C",
          row: 2,
          column: "C",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 2,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "02D",
          row: 2,
          column: "D",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "02E",
          row: 2,
          column: "E",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "02F",
          row: 2,
          column: "F",
          group: 1,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "03A",
          row: 3,
          column: "A",
          group: 1,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "03B",
          row: 3,
          column: "B",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "03C",
          row: 3,
          column: "C",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 3,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "03D",
          row: 3,
          column: "D",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "03E",
          row: 3,
          column: "E",
          group: 1,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "03F",
          row: 3,
          column: "F",
          group: 1,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "04A",
          row: 4,
          column: "A",
          group: 4,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "04B",
          row: 4,
          column: "B",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "04C",
          row: 4,
          column: "C",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 4,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "04D",
          row: 4,
          column: "D",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "04E",
          row: 4,
          column: "E",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "04F",
          row: 4,
          column: "F",
          group: 4,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "05A",
          row: 5,
          column: "A",
          group: 4,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "05B",
          row: 5,
          column: "B",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "05C",
          row: 5,
          column: "C",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 5,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "05D",
          row: 5,
          column: "D",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "05E",
          row: 5,
          column: "E",
          group: 4,
          legend: 4,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "05F",
          row: 5,
          column: "F",
          group: 4,
          legend: 4,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "06A",
          row: 6,
          column: "A",
          group: 5,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "06B",
          row: 6,
          column: "B",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "06C",
          row: 6,
          column: "C",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 6,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "06D",
          row: 6,
          column: "D",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "06E",
          row: 6,
          column: "E",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "06F",
          row: 6,
          column: "F",
          group: 5,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "07A",
          row: 7,
          column: "A",
          group: 5,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "07B",
          row: 7,
          column: "B",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "07C",
          row: 7,
          column: "C",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 7,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "07D",
          row: 7,
          column: "D",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "07E",
          row: 7,
          column: "E",
          group: 5,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "07F",
          row: 7,
          column: "F",
          group: 5,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "08A",
          row: 8,
          column: "A",
          group: 6,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "08B",
          row: 8,
          column: "B",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "08C",
          row: 8,
          column: "C",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 8,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "08D",
          row: 8,
          column: "D",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "08E",
          row: 8,
          column: "E",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "08F",
          row: 8,
          column: "F",
          group: 6,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "09A",
          row: 9,
          column: "A",
          group: 6,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "09B",
          row: 9,
          column: "B",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "09C",
          row: 9,
          column: "C",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 9,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "09D",
          row: 9,
          column: "D",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "09E",
          row: 9,
          column: "E",
          group: 6,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "09F",
          row: 9,
          column: "F",
          group: 6,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "10A",
          row: 10,
          column: "A",
          group: 7,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "10B",
          row: 10,
          column: "B",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "10C",
          row: 10,
          column: "C",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 10,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "10D",
          row: 10,
          column: "D",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "10E",
          row: 10,
          column: "E",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "10F",
          row: 10,
          column: "F",
          group: 7,
          legend: 7,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "11A",
          row: 11,
          column: "A",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: false,
          showEmergencyExit: false,
        },
        {
          designator: "11B",
          row: 11,
          column: "B",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "11C",
          row: 11,
          column: "C",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 11,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "11D",
          row: 11,
          column: "D",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "11E",
          row: 11,
          column: "E",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "11F",
          row: 11,
          column: "F",
          group: 7,
          legend: 7,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: false,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "12A",
          row: 12,
          column: "A",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          windowSeat: true,
          showEmergencyExit: true,
        },
        {
          designator: "12B",
          row: 12,
          column: "B",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "12C",
          row: 12,
          column: "C",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "AISLE",
          row: 12,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "12D",
          row: 12,
          column: "D",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "12E",
          row: 12,
          column: "E",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "12F",
          row: 12,
          column: "F",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          windowSeat: false,
          showEmergencyExit: true,
        },
      ],
      [
        {
          designator: "13A",
          row: 13,
          column: "A",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          windowSeat: true,
          showEmergencyExit: true,
        },
        {
          designator: "13B",
          row: 13,
          column: "B",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "13C",
          row: 13,
          column: "C",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "AISLE",
          row: 13,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "13D",
          row: 13,
          column: "D",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "13E",
          row: 13,
          column: "E",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          showEmergencyExit: true,
        },
        {
          designator: "13F",
          row: 13,
          column: "F",
          group: 9,
          legend: 13,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: true,
          emergencyExit: true,
          windowSeat: true,
          showEmergencyExit: true,
        },
      ],
      [
        {
          designator: "14A",
          row: 14,
          column: "A",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "14B",
          row: 14,
          column: "B",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "14C",
          row: 14,
          column: "C",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 14,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "14D",
          row: 14,
          column: "D",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "14E",
          row: 14,
          column: "E",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "14F",
          row: 14,
          column: "F",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "15A",
          row: 15,
          column: "A",
          group: 8,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "15B",
          row: 15,
          column: "B",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "15C",
          row: 15,
          column: "C",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 15,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "15D",
          row: 15,
          column: "D",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "15E",
          row: 15,
          column: "E",
          group: 8,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "15F",
          row: 15,
          column: "F",
          group: 8,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "16A",
          row: 16,
          column: "A",
          group: 10,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "16B",
          row: 16,
          column: "B",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "16C",
          row: 16,
          column: "C",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 16,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "16D",
          row: 16,
          column: "D",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "16E",
          row: 16,
          column: "E",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "16F",
          row: 16,
          column: "F",
          group: 10,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "17A",
          row: 17,
          column: "A",
          group: 10,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "17B",
          row: 17,
          column: "B",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "17C",
          row: 17,
          column: "C",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 17,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "17D",
          row: 17,
          column: "D",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "17E",
          row: 17,
          column: "E",
          group: 10,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "17F",
          row: 17,
          column: "F",
          group: 10,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "18A",
          row: 18,
          column: "A",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "18B",
          row: 18,
          column: "B",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "18C",
          row: 18,
          column: "C",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 18,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "18D",
          row: 18,
          column: "D",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "18E",
          row: 18,
          column: "E",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "18F",
          row: 18,
          column: "F",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "19A",
          row: 19,
          column: "A",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "19B",
          row: 19,
          column: "B",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "19C",
          row: 19,
          column: "C",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 19,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "19D",
          row: 19,
          column: "D",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "19E",
          row: 19,
          column: "E",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "19F",
          row: 19,
          column: "F",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "20A",
          row: 20,
          column: "A",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "20B",
          row: 20,
          column: "B",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "20C",
          row: 20,
          column: "C",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 20,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "20D",
          row: 20,
          column: "D",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "20E",
          row: 20,
          column: "E",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "20F",
          row: 20,
          column: "F",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "21A",
          row: 21,
          column: "A",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "21B",
          row: 21,
          column: "B",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "21C",
          row: 21,
          column: "C",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 21,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "21D",
          row: 21,
          column: "D",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "21E",
          row: 21,
          column: "E",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "21F",
          row: 21,
          column: "F",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "22A",
          row: 22,
          column: "A",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "22B",
          row: 22,
          column: "B",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "22C",
          row: 22,
          column: "C",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 22,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "22D",
          row: 22,
          column: "D",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "22E",
          row: 22,
          column: "E",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "22F",
          row: 22,
          column: "F",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "23A",
          row: 23,
          column: "A",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "23B",
          row: 23,
          column: "B",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "23C",
          row: 23,
          column: "C",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 23,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "23D",
          row: 23,
          column: "D",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "23E",
          row: 23,
          column: "E",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "23F",
          row: 23,
          column: "F",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "24A",
          row: 24,
          column: "A",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "24B",
          row: 24,
          column: "B",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "24C",
          row: 24,
          column: "C",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 24,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "24D",
          row: 24,
          column: "D",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "24E",
          row: 24,
          column: "E",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "24F",
          row: 24,
          column: "F",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "25A",
          row: 25,
          column: "A",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "25B",
          row: 25,
          column: "B",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "25C",
          row: 25,
          column: "C",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 25,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "25D",
          row: 25,
          column: "D",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "25E",
          row: 25,
          column: "E",
          group: 2,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "25F",
          row: 25,
          column: "F",
          group: 2,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "26A",
          row: 26,
          column: "A",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "26B",
          row: 26,
          column: "B",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "26C",
          row: 26,
          column: "C",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 26,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "26D",
          row: 26,
          column: "D",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "26E",
          row: 26,
          column: "E",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "26F",
          row: 26,
          column: "F",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "27A",
          row: 27,
          column: "A",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "27B",
          row: 27,
          column: "B",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "27C",
          row: 27,
          column: "C",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 27,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "27D",
          row: 27,
          column: "D",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "27E",
          row: 27,
          column: "E",
          group: 11,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "27F",
          row: 27,
          column: "F",
          group: 11,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "28A",
          row: 28,
          column: "A",
          group: 108,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "28B",
          row: 28,
          column: "B",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "28C",
          row: 28,
          column: "C",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 28,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "28D",
          row: 28,
          column: "D",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "28E",
          row: 28,
          column: "E",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "28F",
          row: 28,
          column: "F",
          group: 108,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "29A",
          row: 29,
          column: "A",
          group: 108,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "29B",
          row: 29,
          column: "B",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "29C",
          row: 29,
          column: "C",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 29,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "29D",
          row: 29,
          column: "D",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "29E",
          row: 29,
          column: "E",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "29F",
          row: 29,
          column: "F",
          group: 108,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
      [
        {
          designator: "30A",
          row: 30,
          column: "A",
          group: 108,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
        {
          designator: "30B",
          row: 30,
          column: "B",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "30C",
          row: 30,
          column: "C",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "AISLE",
          row: 30,
          group: 0,
          legend: 0,
          infantAllowed: false,
          childAllowed: false,
          disabilityAllowed: false,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "30D",
          row: 30,
          column: "D",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "30E",
          row: 30,
          column: "E",
          group: 108,
          legend: 22,
          infantAllowed: false,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          showEmergencyExit: false,
        },
        {
          designator: "30F",
          row: 30,
          column: "F",
          group: 108,
          legend: 22,
          infantAllowed: true,
          childAllowed: true,
          disabilityAllowed: true,
          extraLegRoom: false,
          emergencyExit: false,
          windowSeat: true,
          showEmergencyExit: false,
        },
      ],
    ],
  },
];
